version: '3.8'
services:
  
  database:
    image: 'bitnami/mongodb:latest'
    container_name: picckr_db
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root_user
      - MONGODB_ROOT_PASSWORD=root_password
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-db:/bitnami/mongodb'

volumes:
  mongo-db:

