version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: picckr_db 
    ports:
      - "27017:27017"
    command: --replSet rs0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_password
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:

# how it works?
# navigate to this root folder: db
# run: docker-compose up -d , the container gonna start
# run: mongosh --host localhost --port 27017 --username root_user --password root_password --authenticationDatabase admin , this gonna grant you access to your mongodb databases.
# run: show dbs , this will display your current dbs
